PAGE: Unit Converter
COLOR: #3b82f6
AUTHOR: NOMAD
DATE: 2025-01-15
DESCRIPTION: Offline unit converter
CATEGORY: app
BIGHEADER: Unit Converter
CUSTOMHTML-START
<select id="type" style="width:100%;padding:8px;margin-bottom:12px;border-radius:8px;"> <option value="length">Length</option> <option value="weight">Weight</option> <option value="temp">Temperature</option> </select> <input id="input" type="number" placeholder="Value" style="width:100%;padding:8px;margin-bottom:12px;border-radius:8px;box-sizing:border-box;"> <select id="from" style="width:48%;padding:8px;border-radius:8px;"></select> <select id="to" style="width:48%;padding:8px;border-radius:8px;float:right;"></select> <div style="clear:both;"></div> <button onclick="convert()" style="width:100%;padding:10px;margin:12px 0;background:#3b82f6;color:white;border:none;border-radius:8px;">Convert</button> <div id="result" style="padding:12px;background:#f0fdf4;border-radius:8px;text-align:center;font-size:18px;">—</div> <script>const units={length:[[1,"m"],[0.001,"km"],[100,"cm"],[1000,"mm"],[3.28084,"ft"],[39.3701,"in"]],weight:[[1,"kg"],[1000,"g"],[2.20462,"lb"],[35.274,"oz"]],temp:[[1,"°C"],[1,"°F"],[1,"K"]]};function updateUnits(){let type=document.getElementById("type").value;let fromSel=document.getElementById("from");let toSel=document.getElementById("to");let opts=units[type];fromSel.innerHTML="";toSel.innerHTML="";for(let i=0;i<opts.length;i++){let opt=document.createElement("option");opt.value=i;opt.text=opts[i][1];fromSel.appendChild(opt.cloneNode(true));toSel.appendChild(opt.cloneNode(true));}}function convert(){let type=document.getElementById("type").value;let val=parseFloat(document.getElementById("input").value);let fromIdx=parseInt(document.getElementById("from").value);let toIdx=parseInt(document.getElementById("to").value);let resultDiv=document.getElementById("result");if(isNaN(val)){resultDiv.innerText="Enter a number";return;}if(type=="temp"){let c;if(fromIdx==0)c=val;else if(fromIdx==1)c=(val-32)*5/9;else c=val-273.15;let out;if(toIdx==0)out=c;else if(toIdx==1)out=c*9/5+32;else out=c+273.15;resultDiv.innerText=out.toFixed(2)+" "+units[type][toIdx][1];}else{let base=val/units[type][fromIdx][0];let out=base*units[type][toIdx][0];resultDiv.innerText=out.toFixed(4)+" "+units[type][toIdx][1];}}document.getElementById("type").onchange=updateUnits;updateUnits();</script>
CUSTOMHTML-END